### ISSUE TITLE
Compare results with structural connectivity retrieved from EBRAINS

### ISSUE THREAD

**Issue by dickscheid** [ymzayek/EBRAINS-Connectivity-Analysis#4]
At the end, instead of uploading results (which is not really possible automatically yet), we can compare the result with structural connectivity from EBRAINS, e.g. individual or average streamline counts from HCP cohort.

**Comment by ymzayek** [comment]
This is done in the last step now. It's done only visually which I think should be enough as a starting point to showcase this possibilty
